package com.moyu.core.user.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MoyuHouseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public MoyuHouseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("moyu_house_info.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("moyu_house_info.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("moyu_house_info.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("moyu_house_info.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("moyu_house_info.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("moyu_house_info.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHouseTitleIsNull() {
            addCriterion("moyu_house_info.house_title is null");
            return (Criteria) this;
        }

        public Criteria andHouseTitleIsNotNull() {
            addCriterion("moyu_house_info.house_title is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTitleEqualTo(String value) {
            addCriterion("moyu_house_info.house_title =", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_title <>", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleGreaterThan(String value) {
            addCriterion("moyu_house_info.house_title >", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_title >=", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleLessThan(String value) {
            addCriterion("moyu_house_info.house_title <", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_title <=", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleLike(String value) {
            addCriterion("moyu_house_info.house_title like", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleNotLike(String value) {
            addCriterion("moyu_house_info.house_title not like", value, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleIn(List<String> values) {
            addCriterion("moyu_house_info.house_title in", values, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_title not in", values, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_title between", value1, value2, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseTitleNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_title not between", value1, value2, "houseTitle");
            return (Criteria) this;
        }

        public Criteria andHouseExtIsNull() {
            addCriterion("moyu_house_info.house_ext is null");
            return (Criteria) this;
        }

        public Criteria andHouseExtIsNotNull() {
            addCriterion("moyu_house_info.house_ext is not null");
            return (Criteria) this;
        }

        public Criteria andHouseExtEqualTo(String value) {
            addCriterion("moyu_house_info.house_ext =", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_ext <>", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtGreaterThan(String value) {
            addCriterion("moyu_house_info.house_ext >", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_ext >=", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtLessThan(String value) {
            addCriterion("moyu_house_info.house_ext <", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_ext <=", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtLike(String value) {
            addCriterion("moyu_house_info.house_ext like", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtNotLike(String value) {
            addCriterion("moyu_house_info.house_ext not like", value, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtIn(List<String> values) {
            addCriterion("moyu_house_info.house_ext in", values, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_ext not in", values, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_ext between", value1, value2, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseExtNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_ext not between", value1, value2, "houseExt");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathIsNull() {
            addCriterion("moyu_house_info.house_file_path is null");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathIsNotNull() {
            addCriterion("moyu_house_info.house_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathEqualTo(String value) {
            addCriterion("moyu_house_info.house_file_path =", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_file_path <>", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathGreaterThan(String value) {
            addCriterion("moyu_house_info.house_file_path >", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_file_path >=", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathLessThan(String value) {
            addCriterion("moyu_house_info.house_file_path <", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_file_path <=", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathLike(String value) {
            addCriterion("moyu_house_info.house_file_path like", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathNotLike(String value) {
            addCriterion("moyu_house_info.house_file_path not like", value, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathIn(List<String> values) {
            addCriterion("moyu_house_info.house_file_path in", values, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_file_path not in", values, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_file_path between", value1, value2, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseFilePathNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_file_path not between", value1, value2, "houseFilePath");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceIsNull() {
            addCriterion("moyu_house_info.house_sum_price is null");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceIsNotNull() {
            addCriterion("moyu_house_info.house_sum_price is not null");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_price =", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_price <>", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_sum_price >", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_price >=", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceLessThan(Integer value) {
            addCriterion("moyu_house_info.house_sum_price <", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_price <=", value, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_sum_price in", values, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_sum_price not in", values, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_sum_price between", value1, value2, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseSumPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_sum_price not between", value1, value2, "houseSumPrice");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNull() {
            addCriterion("moyu_house_info.house_location is null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNotNull() {
            addCriterion("moyu_house_info.house_location is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationEqualTo(String value) {
            addCriterion("moyu_house_info.house_location =", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_location <>", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThan(String value) {
            addCriterion("moyu_house_info.house_location >", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_location >=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThan(String value) {
            addCriterion("moyu_house_info.house_location <", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_location <=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLike(String value) {
            addCriterion("moyu_house_info.house_location like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotLike(String value) {
            addCriterion("moyu_house_info.house_location not like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIn(List<String> values) {
            addCriterion("moyu_house_info.house_location in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_location not in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_location between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_location not between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelIsNull() {
            addCriterion("moyu_house_info.house_floor_level is null");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelIsNotNull() {
            addCriterion("moyu_house_info.house_floor_level is not null");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelEqualTo(String value) {
            addCriterion("moyu_house_info.house_floor_level =", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_floor_level <>", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelGreaterThan(String value) {
            addCriterion("moyu_house_info.house_floor_level >", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_floor_level >=", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelLessThan(String value) {
            addCriterion("moyu_house_info.house_floor_level <", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_floor_level <=", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelLike(String value) {
            addCriterion("moyu_house_info.house_floor_level like", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelNotLike(String value) {
            addCriterion("moyu_house_info.house_floor_level not like", value, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelIn(List<String> values) {
            addCriterion("moyu_house_info.house_floor_level in", values, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_floor_level not in", values, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_floor_level between", value1, value2, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseFloorLevelNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_floor_level not between", value1, value2, "houseFloorLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelIsNull() {
            addCriterion("moyu_house_info.house_sum_level is null");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelIsNotNull() {
            addCriterion("moyu_house_info.house_sum_level is not null");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_level =", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_level <>", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_sum_level >", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_level >=", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelLessThan(Integer value) {
            addCriterion("moyu_house_info.house_sum_level <", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_sum_level <=", value, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_sum_level in", values, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_sum_level not in", values, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_sum_level between", value1, value2, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseSumLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_sum_level not between", value1, value2, "houseSumLevel");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeIsNull() {
            addCriterion("moyu_house_info.house_create_time is null");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeIsNotNull() {
            addCriterion("moyu_house_info.house_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeEqualTo(String value) {
            addCriterion("moyu_house_info.house_create_time =", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_create_time <>", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeGreaterThan(String value) {
            addCriterion("moyu_house_info.house_create_time >", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_create_time >=", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeLessThan(String value) {
            addCriterion("moyu_house_info.house_create_time <", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_create_time <=", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeLike(String value) {
            addCriterion("moyu_house_info.house_create_time like", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeNotLike(String value) {
            addCriterion("moyu_house_info.house_create_time not like", value, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeIn(List<String> values) {
            addCriterion("moyu_house_info.house_create_time in", values, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_create_time not in", values, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_create_time between", value1, value2, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseCreateTimeNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_create_time not between", value1, value2, "houseCreateTime");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutIsNull() {
            addCriterion("moyu_house_info.house_layout is null");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutIsNotNull() {
            addCriterion("moyu_house_info.house_layout is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutEqualTo(String value) {
            addCriterion("moyu_house_info.house_layout =", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_layout <>", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutGreaterThan(String value) {
            addCriterion("moyu_house_info.house_layout >", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_layout >=", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutLessThan(String value) {
            addCriterion("moyu_house_info.house_layout <", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_layout <=", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutLike(String value) {
            addCriterion("moyu_house_info.house_layout like", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutNotLike(String value) {
            addCriterion("moyu_house_info.house_layout not like", value, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutIn(List<String> values) {
            addCriterion("moyu_house_info.house_layout in", values, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_layout not in", values, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_layout between", value1, value2, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseLayoutNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_layout not between", value1, value2, "houseLayout");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureIsNull() {
            addCriterion("moyu_house_info.house_measure is null");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureIsNotNull() {
            addCriterion("moyu_house_info.house_measure is not null");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure =", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureNotEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure <>", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureGreaterThan(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure >", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure >=", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureLessThan(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure <", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_measure <=", value, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureIn(List<BigDecimal> values) {
            addCriterion("moyu_house_info.house_measure in", values, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureNotIn(List<BigDecimal> values) {
            addCriterion("moyu_house_info.house_measure not in", values, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moyu_house_info.house_measure between", value1, value2, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseMeasureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moyu_house_info.house_measure not between", value1, value2, "houseMeasure");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationIsNull() {
            addCriterion("moyu_house_info.house_orientation is null");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationIsNotNull() {
            addCriterion("moyu_house_info.house_orientation is not null");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationEqualTo(String value) {
            addCriterion("moyu_house_info.house_orientation =", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_orientation <>", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationGreaterThan(String value) {
            addCriterion("moyu_house_info.house_orientation >", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_orientation >=", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationLessThan(String value) {
            addCriterion("moyu_house_info.house_orientation <", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_orientation <=", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationLike(String value) {
            addCriterion("moyu_house_info.house_orientation like", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationNotLike(String value) {
            addCriterion("moyu_house_info.house_orientation not like", value, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationIn(List<String> values) {
            addCriterion("moyu_house_info.house_orientation in", values, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_orientation not in", values, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_orientation between", value1, value2, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHouseOrientationNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_orientation not between", value1, value2, "houseOrientation");
            return (Criteria) this;
        }

        public Criteria andHousePriceIsNull() {
            addCriterion("moyu_house_info.house_price is null");
            return (Criteria) this;
        }

        public Criteria andHousePriceIsNotNull() {
            addCriterion("moyu_house_info.house_price is not null");
            return (Criteria) this;
        }

        public Criteria andHousePriceEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_price =", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceNotEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_price <>", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceGreaterThan(BigDecimal value) {
            addCriterion("moyu_house_info.house_price >", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_price >=", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceLessThan(BigDecimal value) {
            addCriterion("moyu_house_info.house_price <", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("moyu_house_info.house_price <=", value, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceIn(List<BigDecimal> values) {
            addCriterion("moyu_house_info.house_price in", values, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceNotIn(List<BigDecimal> values) {
            addCriterion("moyu_house_info.house_price not in", values, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moyu_house_info.house_price between", value1, value2, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHousePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("moyu_house_info.house_price not between", value1, value2, "housePrice");
            return (Criteria) this;
        }

        public Criteria andHouseStarIsNull() {
            addCriterion("moyu_house_info.house_star is null");
            return (Criteria) this;
        }

        public Criteria andHouseStarIsNotNull() {
            addCriterion("moyu_house_info.house_star is not null");
            return (Criteria) this;
        }

        public Criteria andHouseStarEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_star =", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_star <>", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_star >", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_star >=", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarLessThan(Integer value) {
            addCriterion("moyu_house_info.house_star <", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_star <=", value, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_star in", values, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_star not in", values, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_star between", value1, value2, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHouseStarNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_star not between", value1, value2, "houseStar");
            return (Criteria) this;
        }

        public Criteria andHousePublishIsNull() {
            addCriterion("moyu_house_info.house_publish is null");
            return (Criteria) this;
        }

        public Criteria andHousePublishIsNotNull() {
            addCriterion("moyu_house_info.house_publish is not null");
            return (Criteria) this;
        }

        public Criteria andHousePublishEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_publish =", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_publish <>", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_publish >", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_publish >=", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishLessThan(Integer value) {
            addCriterion("moyu_house_info.house_publish <", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_publish <=", value, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_publish in", values, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_publish not in", values, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_publish between", value1, value2, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHousePublishNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_publish not between", value1, value2, "housePublish");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeIsNull() {
            addCriterion("moyu_house_info.house_taxfree is null");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeIsNotNull() {
            addCriterion("moyu_house_info.house_taxfree is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeEqualTo(String value) {
            addCriterion("moyu_house_info.house_taxfree =", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_taxfree <>", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeGreaterThan(String value) {
            addCriterion("moyu_house_info.house_taxfree >", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_taxfree >=", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeLessThan(String value) {
            addCriterion("moyu_house_info.house_taxfree <", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_taxfree <=", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeLike(String value) {
            addCriterion("moyu_house_info.house_taxfree like", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeNotLike(String value) {
            addCriterion("moyu_house_info.house_taxfree not like", value, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeIn(List<String> values) {
            addCriterion("moyu_house_info.house_taxfree in", values, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_taxfree not in", values, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_taxfree between", value1, value2, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseTaxfreeNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_taxfree not between", value1, value2, "houseTaxfree");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayIsNull() {
            addCriterion("moyu_house_info.house_subway is null");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayIsNotNull() {
            addCriterion("moyu_house_info.house_subway is not null");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_subway =", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_subway <>", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_subway >", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_subway >=", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayLessThan(Integer value) {
            addCriterion("moyu_house_info.house_subway <", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_subway <=", value, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_subway in", values, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_subway not in", values, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_subway between", value1, value2, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseSubwayNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_subway not between", value1, value2, "houseSubway");
            return (Criteria) this;
        }

        public Criteria andHouseLinkIsNull() {
            addCriterion("moyu_house_info.house_link is null");
            return (Criteria) this;
        }

        public Criteria andHouseLinkIsNotNull() {
            addCriterion("moyu_house_info.house_link is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLinkEqualTo(String value) {
            addCriterion("moyu_house_info.house_link =", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkNotEqualTo(String value) {
            addCriterion("moyu_house_info.house_link <>", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkGreaterThan(String value) {
            addCriterion("moyu_house_info.house_link >", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_link >=", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkLessThan(String value) {
            addCriterion("moyu_house_info.house_link <", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkLessThanOrEqualTo(String value) {
            addCriterion("moyu_house_info.house_link <=", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkLike(String value) {
            addCriterion("moyu_house_info.house_link like", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkNotLike(String value) {
            addCriterion("moyu_house_info.house_link not like", value, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkIn(List<String> values) {
            addCriterion("moyu_house_info.house_link in", values, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkNotIn(List<String> values) {
            addCriterion("moyu_house_info.house_link not in", values, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_link between", value1, value2, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseLinkNotBetween(String value1, String value2) {
            addCriterion("moyu_house_info.house_link not between", value1, value2, "houseLink");
            return (Criteria) this;
        }

        public Criteria andHouseOriginIsNull() {
            addCriterion("moyu_house_info.house_origin is null");
            return (Criteria) this;
        }

        public Criteria andHouseOriginIsNotNull() {
            addCriterion("moyu_house_info.house_origin is not null");
            return (Criteria) this;
        }

        public Criteria andHouseOriginEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_origin =", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_origin <>", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginGreaterThan(Integer value) {
            addCriterion("moyu_house_info.house_origin >", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_origin >=", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginLessThan(Integer value) {
            addCriterion("moyu_house_info.house_origin <", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.house_origin <=", value, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_origin in", values, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.house_origin not in", values, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_origin between", value1, value2, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andHouseOriginNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.house_origin not between", value1, value2, "houseOrigin");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("moyu_house_info.is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("moyu_house_info.is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("moyu_house_info.is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("moyu_house_info.is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("moyu_house_info.is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("moyu_house_info.is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_house_info.is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("moyu_house_info.is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("moyu_house_info.is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_house_info.is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIsNull() {
            addCriterion("moyu_house_info.gtm_created is null");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIsNotNull() {
            addCriterion("moyu_house_info.gtm_created is not null");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedEqualTo(Date value) {
            addCriterion("moyu_house_info.gtm_created =", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotEqualTo(Date value) {
            addCriterion("moyu_house_info.gtm_created <>", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedGreaterThan(Date value) {
            addCriterion("moyu_house_info.gtm_created >", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("moyu_house_info.gtm_created >=", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedLessThan(Date value) {
            addCriterion("moyu_house_info.gtm_created <", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedLessThanOrEqualTo(Date value) {
            addCriterion("moyu_house_info.gtm_created <=", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIn(List<Date> values) {
            addCriterion("moyu_house_info.gtm_created in", values, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotIn(List<Date> values) {
            addCriterion("moyu_house_info.gtm_created not in", values, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedBetween(Date value1, Date value2) {
            addCriterion("moyu_house_info.gtm_created between", value1, value2, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotBetween(Date value1, Date value2) {
            addCriterion("moyu_house_info.gtm_created not between", value1, value2, "gtmCreated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_house_info
     *
     * @mbg.generated do_not_delete_during_merge Mon May 13 10:30:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}