package com.moyu.core.user.domain;

import java.io.Serializable;
import java.util.Date;

public class MyMenu implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private Integer parentId;

    /**
     * 
     */
    private String menuName;

    /**
     * 
     */
    private String menuType;

    /**
     * 
     */
    private String permissionCode;

    /**
     * 
     */
    private String menuUrl;

    /**
     * 
     */
    private Integer menuLever;

    /**
     * 
     */
    private String menuIcon;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 
     */
    private Integer isDel;

    /**
     * 
     */
    private Date gtmCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    private static final long serialVersionUID = 7344245653275880271L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getMenuName() {
        return menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuType() {
        return menuType;
    }

    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getMenuUrl() {
        return menuUrl;
    }

    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    public Integer getMenuLever() {
        return menuLever;
    }

    public void setMenuLever(Integer menuLever) {
        this.menuLever = menuLever;
    }

    public String getMenuIcon() {
        return menuIcon;
    }

    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getIsDel() {
        return isDel;
    }

    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    public Date getGtmCreated() {
        return gtmCreated;
    }

    public void setGtmCreated(Date gtmCreated) {
        this.gtmCreated = gtmCreated;
    }
}