package com.moyu.core.user.domain;

import java.io.Serializable;
import java.util.Date;

public class MyRole implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 
     */
    private String roleName;

    /**
     * 
     */
    private String description;

    /**
     * 
     */
    private Integer isDel;

    /**
     * 
     */
    private Date gtmCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_role
     *
     * @mbg.generated Wed May 08 17:11:58 CST 2019
     */
    private static final long serialVersionUID = 2910743594161370668L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getIsDel() {
        return isDel;
    }

    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    public Date getGtmCreated() {
        return gtmCreated;
    }

    public void setGtmCreated(Date gtmCreated) {
        this.gtmCreated = gtmCreated;
    }
}