package com.moyu.core.user.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MyUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public MyUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("moyu_user.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("moyu_user.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("moyu_user.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("moyu_user.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("moyu_user.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("moyu_user.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("moyu_user.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("moyu_user.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("moyu_user.login_name is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("moyu_user.login_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("moyu_user.login_name =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("moyu_user.login_name <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("moyu_user.login_name >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.login_name >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("moyu_user.login_name <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.login_name <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("moyu_user.login_name like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("moyu_user.login_name not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("moyu_user.login_name in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("moyu_user.login_name not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("moyu_user.login_name between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("moyu_user.login_name not between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("moyu_user.password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("moyu_user.password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("moyu_user.password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("moyu_user.password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("moyu_user.password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("moyu_user.password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("moyu_user.password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("moyu_user.password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("moyu_user.password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("moyu_user.password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("moyu_user.password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("moyu_user.password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("moyu_user.real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("moyu_user.real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("moyu_user.real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("moyu_user.real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("moyu_user.real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("moyu_user.real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("moyu_user.real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("moyu_user.real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("moyu_user.real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("moyu_user.real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("moyu_user.real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("moyu_user.real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("moyu_user.phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("moyu_user.phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("moyu_user.phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("moyu_user.phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("moyu_user.phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("moyu_user.phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("moyu_user.phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("moyu_user.phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("moyu_user.phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("moyu_user.phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("moyu_user.phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("moyu_user.phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andLockAccountIsNull() {
            addCriterion("moyu_user.lock_account is null");
            return (Criteria) this;
        }

        public Criteria andLockAccountIsNotNull() {
            addCriterion("moyu_user.lock_account is not null");
            return (Criteria) this;
        }

        public Criteria andLockAccountEqualTo(Integer value) {
            addCriterion("moyu_user.lock_account =", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountNotEqualTo(Integer value) {
            addCriterion("moyu_user.lock_account <>", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountGreaterThan(Integer value) {
            addCriterion("moyu_user.lock_account >", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.lock_account >=", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountLessThan(Integer value) {
            addCriterion("moyu_user.lock_account <", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.lock_account <=", value, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountIn(List<Integer> values) {
            addCriterion("moyu_user.lock_account in", values, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountNotIn(List<Integer> values) {
            addCriterion("moyu_user.lock_account not in", values, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.lock_account between", value1, value2, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andLockAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.lock_account not between", value1, value2, "lockAccount");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("moyu_user.salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("moyu_user.salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("moyu_user.salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("moyu_user.salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("moyu_user.salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("moyu_user.salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("moyu_user.salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("moyu_user.salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("moyu_user.salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("moyu_user.salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("moyu_user.salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("moyu_user.salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("moyu_user.address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("moyu_user.address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("moyu_user.address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("moyu_user.address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("moyu_user.address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("moyu_user.address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("moyu_user.address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("moyu_user.address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("moyu_user.address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("moyu_user.address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("moyu_user.address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("moyu_user.address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("moyu_user.address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("moyu_user.address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("moyu_user.state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("moyu_user.state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("moyu_user.state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("moyu_user.state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("moyu_user.state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("moyu_user.state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("moyu_user.state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("moyu_user.state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("moyu_user.is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("moyu_user.is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("moyu_user.is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("moyu_user.is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("moyu_user.is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("moyu_user.is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("moyu_user.is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("moyu_user.is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("moyu_user.is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("moyu_user.is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIsNull() {
            addCriterion("moyu_user.gtm_created is null");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIsNotNull() {
            addCriterion("moyu_user.gtm_created is not null");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedEqualTo(Date value) {
            addCriterion("moyu_user.gtm_created =", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotEqualTo(Date value) {
            addCriterion("moyu_user.gtm_created <>", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedGreaterThan(Date value) {
            addCriterion("moyu_user.gtm_created >", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("moyu_user.gtm_created >=", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedLessThan(Date value) {
            addCriterion("moyu_user.gtm_created <", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedLessThanOrEqualTo(Date value) {
            addCriterion("moyu_user.gtm_created <=", value, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedIn(List<Date> values) {
            addCriterion("moyu_user.gtm_created in", values, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotIn(List<Date> values) {
            addCriterion("moyu_user.gtm_created not in", values, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedBetween(Date value1, Date value2) {
            addCriterion("moyu_user.gtm_created between", value1, value2, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andGtmCreatedNotBetween(Date value1, Date value2) {
            addCriterion("moyu_user.gtm_created not between", value1, value2, "gtmCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedIsNull() {
            addCriterion("moyu_user.modify_created is null");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedIsNotNull() {
            addCriterion("moyu_user.modify_created is not null");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedEqualTo(Date value) {
            addCriterion("moyu_user.modify_created =", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedNotEqualTo(Date value) {
            addCriterion("moyu_user.modify_created <>", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedGreaterThan(Date value) {
            addCriterion("moyu_user.modify_created >", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("moyu_user.modify_created >=", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedLessThan(Date value) {
            addCriterion("moyu_user.modify_created <", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedLessThanOrEqualTo(Date value) {
            addCriterion("moyu_user.modify_created <=", value, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedIn(List<Date> values) {
            addCriterion("moyu_user.modify_created in", values, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedNotIn(List<Date> values) {
            addCriterion("moyu_user.modify_created not in", values, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedBetween(Date value1, Date value2) {
            addCriterion("moyu_user.modify_created between", value1, value2, "modifyCreated");
            return (Criteria) this;
        }

        public Criteria andModifyCreatedNotBetween(Date value1, Date value2) {
            addCriterion("moyu_user.modify_created not between", value1, value2, "modifyCreated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 25 12:25:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}