package com.moyu.core.user.dao.mapper;

import com.moyu.core.user.domain.MoyuHouseInfo;
import com.moyu.core.user.domain.MoyuHouseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoyuHouseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    long countByExample(MoyuHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int deleteByExample(MoyuHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int insert(MoyuHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int insertSelective(MoyuHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    List<MoyuHouseInfo> selectByExample(MoyuHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    MoyuHouseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") MoyuHouseInfo record, @Param("example") MoyuHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int updateByExample(@Param("record") MoyuHouseInfo record, @Param("example") MoyuHouseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int updateByPrimaryKeySelective(MoyuHouseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    int updateByPrimaryKey(MoyuHouseInfo record);
}