package com.moyu.core.user.dao.mapper;

import com.moyu.core.user.domain.MyMenu;
import com.moyu.core.user.domain.MyMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    long countByExample(MyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int deleteByExample(MyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insert(MyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insertSelective(MyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    List<MyMenu> selectByExample(MyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyMenu record, @Param("example") MyMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_menu
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExample(@Param("record") MyMenu record, @Param("example") MyMenuExample example);
}