package com.moyu.core.user.dao.mapper;

import com.moyu.core.user.domain.MyRoleMenuRelation;
import com.moyu.core.user.domain.MyRoleMenuRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyRoleMenuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    long countByExample(MyRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int deleteByExample(MyRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insert(MyRoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insertSelective(MyRoleMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    List<MyRoleMenuRelation> selectByExample(MyRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyRoleMenuRelation record, @Param("example") MyRoleMenuRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_role_menu_relation
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExample(@Param("record") MyRoleMenuRelation record, @Param("example") MyRoleMenuRelationExample example);
}