package com.moyu.core.user.dao.mapper;

import com.moyu.core.user.domain.MyUser;
import com.moyu.core.user.domain.MyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    long countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    List<MyUser> selectByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moyu_user
     *
     * @mbg.generated Fri Jan 25 12:25:43 CST 2019
     */
    int updateByExample(@Param("record") MyUser record, @Param("example") MyUserExample example);
}