package com.moyu.crawler.beike.domian;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MoyuHouseInfo implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 标题
     */
    private String houseTitle;

    /**
     * 低楼层(共33层) | 2011年建 | 3室2厅 | 85.86平米 | 南 


 高楼层(共7层) 2室2厅 | 67.73平米 | 南

分割格式不同
     */
    private String houseExt;

    /**
     * 图片
     */
    private String houseFilePath;

    /**
     * 总价格 单位：万
     */
    private Integer houseSumPrice;

    /**
     * 位置
     */
    private String houseLocation;

    /**
     * 楼层分级
     */
    private String houseFloorLevel;

    /**
     * 总楼层
     */
    private Integer houseSumLevel;

    /**
     * 房屋建成时间
     */
    private String houseCreateTime;

    /**
     * 房间布局，一室一厅等
     */
    private String houseLayout;

    /**
     * 房屋面积
     */
    private BigDecimal houseMeasure;

    /**
     * 房屋朝向
     */
    private String houseOrientation;

    /**
     * 单价 XXX元/平米
     */
    private BigDecimal housePrice;

    /**
     * XXX人关注
     */
    private Integer houseStar;

    /**
     * XXX月前发布
     */
    private Integer housePublish;

    /**
     * 免税条件优惠
     */
    private String houseTaxfree;

    /**
     * 0 是 1否  ;近地铁
     */
    private Integer houseSubway;

    /**
     * 房屋链接
     */
    private String houseLink;

    /**
     * 0 贝壳 ;房屋来源
     */
    private Integer houseOrigin;

    /**
     * 
     */
    private Integer isDel;

    /**
     * 
     */
    private Date gtmCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table moyu_house_info
     *
     * @mbg.generated Mon May 13 10:30:09 CST 2019
     */
    private static final long serialVersionUID = -1167744190641688871L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getHouseTitle() {
        return houseTitle;
    }

    public void setHouseTitle(String houseTitle) {
        this.houseTitle = houseTitle;
    }

    public String getHouseExt() {
        return houseExt;
    }

    public void setHouseExt(String houseExt) {
        this.houseExt = houseExt;
    }

    public String getHouseFilePath() {
        return houseFilePath;
    }

    public void setHouseFilePath(String houseFilePath) {
        this.houseFilePath = houseFilePath;
    }

    public Integer getHouseSumPrice() {
        return houseSumPrice;
    }

    public void setHouseSumPrice(Integer houseSumPrice) {
        this.houseSumPrice = houseSumPrice;
    }

    public String getHouseLocation() {
        return houseLocation;
    }

    public void setHouseLocation(String houseLocation) {
        this.houseLocation = houseLocation;
    }

    public String getHouseFloorLevel() {
        return houseFloorLevel;
    }

    public void setHouseFloorLevel(String houseFloorLevel) {
        this.houseFloorLevel = houseFloorLevel;
    }

    public Integer getHouseSumLevel() {
        return houseSumLevel;
    }

    public void setHouseSumLevel(Integer houseSumLevel) {
        this.houseSumLevel = houseSumLevel;
    }

    public String getHouseCreateTime() {
        return houseCreateTime;
    }

    public void setHouseCreateTime(String houseCreateTime) {
        this.houseCreateTime = houseCreateTime;
    }

    public String getHouseLayout() {
        return houseLayout;
    }

    public void setHouseLayout(String houseLayout) {
        this.houseLayout = houseLayout;
    }

    public BigDecimal getHouseMeasure() {
        return houseMeasure;
    }

    public void setHouseMeasure(BigDecimal houseMeasure) {
        this.houseMeasure = houseMeasure;
    }

    public String getHouseOrientation() {
        return houseOrientation;
    }

    public void setHouseOrientation(String houseOrientation) {
        this.houseOrientation = houseOrientation;
    }

    public BigDecimal getHousePrice() {
        return housePrice;
    }

    public void setHousePrice(BigDecimal housePrice) {
        this.housePrice = housePrice;
    }

    public Integer getHouseStar() {
        return houseStar;
    }

    public void setHouseStar(Integer houseStar) {
        this.houseStar = houseStar;
    }

    public Integer getHousePublish() {
        return housePublish;
    }

    public void setHousePublish(Integer housePublish) {
        this.housePublish = housePublish;
    }

    public String getHouseTaxfree() {
        return houseTaxfree;
    }

    public void setHouseTaxfree(String houseTaxfree) {
        this.houseTaxfree = houseTaxfree;
    }

    public Integer getHouseSubway() {
        return houseSubway;
    }

    public void setHouseSubway(Integer houseSubway) {
        this.houseSubway = houseSubway;
    }

    public String getHouseLink() {
        return houseLink;
    }

    public void setHouseLink(String houseLink) {
        this.houseLink = houseLink;
    }

    public Integer getHouseOrigin() {
        return houseOrigin;
    }

    public void setHouseOrigin(Integer houseOrigin) {
        this.houseOrigin = houseOrigin;
    }

    public Integer getIsDel() {
        return isDel;
    }

    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    public Date getGtmCreated() {
        return gtmCreated;
    }

    public void setGtmCreated(Date gtmCreated) {
        this.gtmCreated = gtmCreated;
    }
}